version: "3"

services:
  app:
    container_name: docker-MEN-jest-server
    restart: always
    build: .
    ports:
      - "80:8082"
    links:
      - mongo
  mongo:
    container_name: docker-MEN-jest-mongo
    image: mongo
    ports:
      - "27017:27017"
